In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, RocCurveDisplay, auc
import tensorflow as tf
from MyNeuralWeb_Final import NeuralWeb
from sklearn.preprocessing import RobustScaler

from sklearn.datasets import fetch_california_housing

In [3]:
df = pd.read_csv('../Data/dataset_regression.csv')
df.drop(['Unnamed: 0'], axis=1, inplace=True)
df.isnull().sum().sum()

0

In [4]:
y = df["price_usd"]
X = df.drop(["price_usd"], axis=1)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3)
layers_dims = [29, 4, 1]

In [6]:
neuron = NeuralWeb(layers_dims,  learning_rate=0.0005, num_iterations = 3)
train = neuron.iterations(X_train, y_train)

Param {'W1': array([[ 0.30163336, -0.11360031, -0.09807903, -0.19924527,  0.16070216,
        -0.42738501,  0.32400341, -0.14135257,  0.05924407, -0.04630692,
         0.27150663, -0.38255853, -0.05987137, -0.0713171 ,  0.2105357 ,
        -0.20424468, -0.03201911, -0.16301422,  0.0078389 ,  0.10822607,
        -0.20437985,  0.21256986,  0.16742119,  0.09331086,  0.16728475,
        -0.12696508, -0.02282014, -0.17376802, -0.04974557],
       [ 0.09848454, -0.12843818, -0.07367528, -0.12760477, -0.15695075,
        -0.12464728, -0.00235176, -0.20747932,  0.0435299 ,  0.30821753,
         0.13779414, -0.03562297, -0.16482856, -0.13874381,  0.31428093,
         0.00943476, -0.11828712,  0.03545212,  0.39000759,  0.02231296,
         0.11461174,  0.05574023, -0.06541115, -0.2121603 , -0.06487131,
        -0.03879069,  0.10893319,  0.15579531,  0.17290132],
       [ 0.05303223,  0.16436659, -0.14008818,  0.23265178,  0.09524868,
        -0.05535445,  0.09071554, -0.01403331,  0.2101383 ,  0

In [7]:
pred_test = neuron.predict_regr(X_test, train[0])

print("X_trainnnnnnnnnnn\n", X_train.to_numpy())
# print(len(pred_test))
# print(y_test.shape)
print("PRED_TEST", pred_test)
print("Y_test", y_test.to_numpy())
# print(classification_report(y_test, pred_test))

Z [[-4.96943263e+07 -4.78308131e+07 -3.47870443e+07 ... -3.65261306e+07
  -1.87815571e+07 -2.74574305e+07]
 [-6.30608391e+04 -6.06867850e+04 -4.42971604e+04 ... -4.64463145e+04
  -2.39768378e+04 -3.49819528e+04]
 [-4.97215282e+07 -4.78569925e+07 -3.48057070e+07 ... -3.65458649e+07
  -1.87914168e+07 -2.74720774e+07]
 [-4.97446628e+07 -4.78792546e+07 -3.48219842e+07 ... -3.65629065e+07
  -1.88001388e+07 -2.74848879e+07]]
A
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

relu

Z [[-2.88929152 -2.88929152 -2.88929152 ... -2.88929152 -2.88929152
  -2.88929152]]
A
 [[-2.88929152 -2.88929152 -2.88929152 ... -2.88929152 -2.88929152
  -2.88929152]]

line

AL
 [[-2.88929152 -2.88929152 -2.88929152 ... -2.88929152 -2.88929152
  -2.88929152]]
X_trainnnnnnnnnnn
 [[ 30. 503.   0. ...   0.   1. 160.]
 [ 21. 301.   0. ...   0.   1. 148.]
 [ 51. 903.   0. ...   0.   1.  56.]
 ...
 [ 32. 555.   0. ...   1.   0.  86.]
 [  1.  10.   0. ...   0.   1.  