In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import roc_auc_score
from sklearn import metrics
from sklearn import svm, datasets
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV

In [2]:
df = pd.read_csv('../data/balanced_sclaer_dataset_diabetes.csv')

In [3]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [4]:
y = df["Diabetes_012"]
X = df.drop(["Diabetes_012"], axis=1)

In [5]:
y

0         0.0
1         2.0
2         0.0
3         0.0
4         2.0
         ... 
105286    1.0
105287    1.0
105288    1.0
105289    1.0
105290    1.0
Name: Diabetes_012, Length: 105291, dtype: float64

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3)

In [7]:
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics.pairwise import distance_metrics

In [8]:
knn_optimal = GridSearchCV(KNeighborsClassifier(), 
                                             {'n_neighbors': np.arange(3, 5, 1),
                                              'p': np.arange(1, 2, 1),
                                              "metric" : ["euclidean", "minkowski"]
                                              },
                                              ).fit(X_train, y_train)

In [9]:
# knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)

In [10]:
knn_optimal.fit(X_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'minkowski'],
                         'n_neighbors': array([3, 4]), 'p': array([1])})

In [11]:
pred_train = knn_optimal.predict(X_test)

In [12]:
X_test

HighBP  HighChol  CholCheck       BMI    Smoker    Stroke  \
68575     1.0  1.000000        1.0  0.255814  1.000000  0.000000   
49452     1.0  1.000000        1.0  0.302326  0.000000  0.000000   
84448     1.0  1.000000        1.0  0.143057  1.000000  0.348569   
98730     1.0  0.109859        1.0  0.477891  1.000000  0.000000   
36970     1.0  0.000000        1.0  0.476744  1.000000  0.000000   
...       ...       ...        ...       ...       ...       ...   
98246     1.0  0.000000        1.0  0.323560  0.956543  0.000000   
66108     1.0  1.000000        1.0  0.162791  1.000000  0.000000   
7348      1.0  1.000000        1.0  0.453488  0.000000  0.000000   
83533     1.0  1.000000        1.0  0.242702  1.000000  0.000000   
66342     0.0  1.000000        1.0  0.220930  0.000000  0.000000   

       HeartDiseaseorAttack  PhysActivity    Fruits   Veggies  ...  \
68575               0.00000      0.000000  1.000000  1.000000  ...   
49452               0.00000      1.000000  1.000000  1.000000  ...   
84448               1.00000      1.000000  0.000000  0.651431  ...   
98730               0.00000      0.890141  0.890141  0.890141  ...   
36970               0.00000      0.000000  0.000000  1.000000  ...   
...                     ...           ...       ...       ...  ...   
98246               0.00000      1.000000  0.956543  0.956543  ...   
66108               0.00000      1.000000  1.000000  1.000000  ...   
7348                0.00000      0.000000  0.000000  1.000000  ...   
83533               0.56381      0.436190  0.000000  1.000000  ...   
66342               0.00000      1.000000  0.000000  1.000000  ...   

       AnyHealthcare  NoDocbcCost   GenHlth  MentHlth  PhysHlth  DiffWalk  \
68575            1.0     0.000000  0.500000  0.000000  0.100000  0.000000   
49452            1.0     0.000000  0.500000  1.000000  0.000000  0.000000   
84448            1.0     0.651431  1.000000  0.000000  1.000000  1.000000   
98730            1.0     0.890141  0.750000  0.369953  0.262629  1.000000   
36970            1.0     0.000000  0.750000  0.333333  1.000000  1.000000   
...              ...          ...       ...       ...       ...       ...   
98246            1.0     0.956543  0.978271  0.095654  1.000000  0.956543   
66108            1.0     0.000000  0.750000  0.000000  1.000000  1.000000   
7348             1.0     0.000000  0.250000  0.033333  0.033333  0.000000   
83533            1.0     0.000000  0.468095  0.147873  1.000000  0.000000   
66342            1.0     1.000000  0.500000  0.033333  0.000000  0.000000   

           Sex       Age  Education    Income  
68575  0.00000  0.500000   1.000000  0.571429  
49452  0.00000  0.666667   0.800000  0.285714  
84448  1.00000  0.750000   0.600000  0.335510  
98730  0.00000  0.592488   0.800000  0.270020  
36970  1.00000  0.500000   1.000000  0.571429  
...        ...       ...        ...       ...  
98246  0.00000  0.416667   0.617383  0.720494  
66108  0.00000  0.916667   0.800000  0.000000  
7348   0.00000  0.750000   1.000000  1.000000  
83533  0.56381  0.796984   1.000000  0.919456  
66342  1.00000  0.416667   1.000000  1.000000  

[35097 rows x 21 columns]

In [13]:
pred_train

array([2., 2., 1., ..., 2., 1., 0.])

In [14]:
print("NO diabet", sum(pred_train==0))
print("PRE diabet", sum(pred_train==1))
print("YES diabet", sum(pred_train==2))

NO diabet 11358
PRE diabet 12183
YES diabet 11556


In [15]:
#MY_CLASSIFIER

In [16]:
# from MyKnnClassifier import MyKnnClassifier
# from MyKnnClassifier import euclid_distance

In [17]:
#MYMETRICS

In [18]:
# from Metrics import my_accuracy_score

In [19]:
# from Metrics import Metrics

In [20]:
# Metrics.my_precision(pred_train, y_test)

In [21]:
#SKLEARN_METRIC

In [22]:
#Accuracy
accuracy_score(y_test, pred_train)

0.7746246117901815

In [23]:
#Metrics
print(classification_report(y_test, pred_train))

              precision    recall  f1-score   support

         0.0       0.68      0.66      0.67     11709
         1.0       0.95      1.00      0.97     11622
         2.0       0.68      0.67      0.67     11766

    accuracy                           0.77     35097
   macro avg       0.77      0.78      0.77     35097
weighted avg       0.77      0.77      0.77     35097



In [28]:
import pickle 

In [29]:
knnPickle = open('knnpickle_file', 'wb') 

In [30]:
pickle.dump(knn_optimal, knnPickle)

In [31]:
knnPickle.close()

In [24]:
#Conf_matrix
confusion_matrix(y_test, pred_train)

array([[ 7751,   251,  3707],
       [   29, 11590,     3],
       [ 3578,   342,  7846]], dtype=int64)

## ROC AUC

In [25]:
pred_prob = knn_optimal.predict_proba(X_test)

In [26]:
pred_prob

array([[0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.        ],
       ...,
       [0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.        ],
       [0.66666667, 0.33333333, 0.        ]])

In [27]:
macro_roc_auc_ovr = roc_auc_score(
    y_test,
    pred_prob,
    multi_class="ovr",
    average="micro"
)

print(f"Macro-averaged One-vs-Rest ROC AUC score:\n{macro_roc_auc_ovr:.2f}")

Macro-averaged One-vs-Rest ROC AUC score:
0.90
