In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import roc_auc_score
from sklearn import metrics
from sklearn import svm, datasets
from sklearn.model_selection import RandomizedSearchCV

In [2]:
df = pd.read_csv('../data/balanced_sclaer_dataset_diabetes.csv')

In [3]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [4]:
df

HighBP  HighChol  CholCheck       BMI    Smoker  Stroke  \
0       1.000000  0.000000   1.000000  0.279070  0.000000     0.0   
1       0.000000  1.000000   1.000000  0.162791  0.000000     0.0   
2       0.000000  1.000000   1.000000  0.174419  0.000000     0.0   
3       1.000000  0.000000   1.000000  0.279070  1.000000     0.0   
4       0.000000  1.000000   1.000000  0.337209  0.000000     0.0   
...          ...       ...        ...       ...       ...     ...   
105286  0.458320  0.458320   1.000000  0.388081  0.458320     0.0   
105287  1.000000  1.000000   1.000000  0.234238  1.000000     0.0   
105288  0.614436  1.000000   0.614436  0.186047  0.385564     0.0   
105289  1.000000  1.000000   0.149867  0.106394  0.000000     0.0   
105290  0.000000  0.112782   1.000000  0.280381  0.887218     0.0   

        HeartDiseaseorAttack  PhysActivity    Fruits  Veggies  ...  \
0                        0.0      1.000000  0.000000      1.0  ...   
1                        0.0      0.000000  1.000000      1.0  ...   
2                        0.0      0.000000  1.000000      1.0  ...   
3                        0.0      1.000000  1.000000      1.0  ...   
4                        0.0      1.000000  1.000000      1.0  ...   
...                      ...           ...       ...      ...  ...   
105286                   0.0      0.541680  0.541680      1.0  ...   
105287                   0.0      1.000000  1.000000      1.0  ...   
105288                   0.0      0.614436  0.614436      1.0  ...   
105289                   0.0      0.149867  1.000000      0.0  ...   
105290                   0.0      0.887218  0.112782      1.0  ...   

        NoDocbcCost   GenHlth  MentHlth  PhysHlth  DiffWalk       Sex  \
0          0.000000  0.250000  0.000000  0.000000  0.000000  1.000000   
1          0.000000  0.500000  0.000000  0.000000  0.000000  1.000000   
2          0.000000  0.500000  0.000000  0.000000  0.000000  0.000000   
3          0.000000  0.500000  0.066667  0.000000  0.000000  1.000000   
4          0.000000  0.750000  0.000000  0.166667  0.000000  0.000000   
...             ...       ...       ...       ...       ...       ...   
105286     0.000000  0.750000  0.000000  0.590280  0.458320  0.000000   
105287     0.000000  0.500000  0.000000  0.000000  0.000000  0.144427   
105288     0.385564  0.653609  0.192371  0.079519  0.614436  0.385564   
105289     0.000000  0.425066  0.000000  0.056676  0.000000  1.000000   
105290     0.000000  0.471805  0.000000  0.000000  0.000000  0.000000   

             Age  Education    Income  Diabetes_012  
0       0.750000   1.000000  0.857143           0.0  
1       0.333333   1.000000  1.000000           0.0  
2       1.000000   0.800000  0.714286           2.0  
3       0.750000   0.800000  0.714286           2.0  
4       0.583333   0.600000  0.571429           2.0  
...          ...        ...       ...           ...  
105286  0.312493   0.908336  1.000000           1.0  
105287  0.654631   0.828885  1.000000           1.0  
105288  0.602406   0.600000  0.000000           1.0  
105289  0.570844   0.940053  0.978590           1.0  
105290  0.759398   1.000000  1.000000           1.0  

[105291 rows x 22 columns]

In [5]:
y = df["Diabetes_012"]
X = df.drop(["Diabetes_012"], axis=1)

In [6]:
y

0         0.0
1         0.0
2         2.0
3         2.0
4         2.0
         ... 
105286    1.0
105287    1.0
105288    1.0
105289    1.0
105290    1.0
Name: Diabetes_012, Length: 105291, dtype: float64

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3)

In [8]:
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics.pairwise import distance_metrics

In [9]:
knn_optimal = RandomizedSearchCV(KNeighborsClassifier(), 
                                             {'n_neighbors': np.arange(3, 5, 1),
                                              'p': np.arange(1, 2, 1),
                                              "metric" : ["euclidean", "minkowski"]
                                              },
                                              n_iter=10,
                                              random_state=20
                                              ).fit(X_train, y_train)

d:\Machine_Learning\ML\venv\lib\site-packages\sklearn\model_selection\_search.py:305: UserWarning: The total space of parameters 4 is smaller than n_iter=10. Running 4 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


In [10]:
# knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)

In [11]:
knn_optimal.fit(X_train, y_train)

d:\Machine_Learning\ML\venv\lib\site-packages\sklearn\model_selection\_search.py:305: UserWarning: The total space of parameters 4 is smaller than n_iter=10. Running 4 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


RandomizedSearchCV(estimator=KNeighborsClassifier(),
                   param_distributions={'metric': ['euclidean', 'minkowski'],
                                        'n_neighbors': array([3, 4]),
                                        'p': array([1])},
                   random_state=20)

In [12]:
pred_train = knn_optimal.predict(X_test)

In [13]:
pred_train

array([0., 2., 2., ..., 0., 1., 0.])

In [14]:
print("NO diabet", sum(pred_train==0))
print("PRE diabet", sum(pred_train==1))
print("YES diabet", sum(pred_train==2))

NO diabet 11265
PRE diabet 12226
YES diabet 11606


In [15]:
#MYMETRICS

In [16]:
# from Metrics import my_accuracy_score

In [17]:
# from Metrics import Metrics

In [18]:
# Metrics.my_precision(pred_train, y_test)

In [42]:
y_test.to_numpy().shape

(35097,)

In [41]:
pred_train.shape

(35097,)

In [21]:
#SKLEARN_METRIC

In [22]:
#Accuracy
accuracy_score(y_test, pred_train)

0.7774168732370288

In [23]:
#Metrics
print(classification_report(y_test, pred_train))

              precision    recall  f1-score   support

         0.0       0.68      0.66      0.67     11633
         1.0       0.96      1.00      0.98     11758
         2.0       0.68      0.67      0.67     11706

    accuracy                           0.78     35097
   macro avg       0.77      0.78      0.77     35097
weighted avg       0.77      0.78      0.78     35097



In [24]:
#Conf_matrix
confusion_matrix(y_test, pred_train)

array([[ 7707,   202,  3724],
       [   30, 11712,    16],
       [ 3528,   312,  7866]], dtype=int64)

## ROC AUC

In [25]:
pred_prob = knn_optimal.predict_proba(X_test)

In [26]:
pred_prob

array([[0.66666667, 0.        , 0.33333333],
       [0.33333333, 0.        , 0.66666667],
       [0.33333333, 0.        , 0.66666667],
       ...,
       [0.66666667, 0.        , 0.33333333],
       [0.        , 1.        , 0.        ],
       [0.66666667, 0.        , 0.33333333]])

In [27]:
macro_roc_auc_ovr = roc_auc_score(
    y_test,
    pred_prob,
    multi_class="ovr",
    average="micro"
)

print(f"Macro-averaged One-vs-Rest ROC AUC score:\n{macro_roc_auc_ovr:.2f}")

Macro-averaged One-vs-Rest ROC AUC score:
0.90


In [28]:
#SVM

In [29]:
X_train_svm = X_train.iloc[0:2000, :]

In [30]:
y_train_svm = y_train.iloc[0:2000]

In [31]:
X_train_svm.shape

(2000, 21)

In [32]:
y_train_svm.shape

(2000,)

In [33]:
X_test_svm = X_test.iloc[0:600]

In [34]:
y_test_svm = y_test.iloc[0:600]

In [35]:
X_test_svm.shape

(600, 21)

In [36]:
#SVM
rbf = svm.SVC(kernel='rbf').fit(X_train_svm, y_train_svm)

In [37]:
rbf_pred = rbf.predict(X_test_svm)

In [38]:
rbf_pred.shape

(600,)

In [39]:
rbf_accuracy = accuracy_score(y_test_svm, rbf_pred)

In [40]:
rbf_accuracy

0.6983333333333334