In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import roc_auc_score
from sklearn import metrics

In [2]:
df = pd.read_csv('../data/balanced_sclaer_dataset_diabetes.csv')

In [4]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [5]:
df

HighBP  HighChol  CholCheck       BMI    Smoker  Stroke  \
0       1.000000  0.000000   1.000000  0.279070  0.000000     0.0   
1       0.000000  1.000000   1.000000  0.162791  0.000000     0.0   
2       0.000000  1.000000   1.000000  0.174419  0.000000     0.0   
3       1.000000  0.000000   1.000000  0.279070  1.000000     0.0   
4       0.000000  1.000000   1.000000  0.337209  0.000000     0.0   
...          ...       ...        ...       ...       ...     ...   
105286  0.458320  0.458320   1.000000  0.388081  0.458320     0.0   
105287  1.000000  1.000000   1.000000  0.234238  1.000000     0.0   
105288  0.614436  1.000000   0.614436  0.186047  0.385564     0.0   
105289  1.000000  1.000000   0.149867  0.106394  0.000000     0.0   
105290  0.000000  0.112782   1.000000  0.280381  0.887218     0.0   

        HeartDiseaseorAttack  PhysActivity    Fruits  Veggies  ...  \
0                        0.0      1.000000  0.000000      1.0  ...   
1                        0.0      0.000000  1.000000      1.0  ...   
2                        0.0      0.000000  1.000000      1.0  ...   
3                        0.0      1.000000  1.000000      1.0  ...   
4                        0.0      1.000000  1.000000      1.0  ...   
...                      ...           ...       ...      ...  ...   
105286                   0.0      0.541680  0.541680      1.0  ...   
105287                   0.0      1.000000  1.000000      1.0  ...   
105288                   0.0      0.614436  0.614436      1.0  ...   
105289                   0.0      0.149867  1.000000      0.0  ...   
105290                   0.0      0.887218  0.112782      1.0  ...   

        NoDocbcCost   GenHlth  MentHlth  PhysHlth  DiffWalk       Sex  \
0          0.000000  0.250000  0.000000  0.000000  0.000000  1.000000   
1          0.000000  0.500000  0.000000  0.000000  0.000000  1.000000   
2          0.000000  0.500000  0.000000  0.000000  0.000000  0.000000   
3          0.000000  0.500000  0.066667  0.000000  0.000000  1.000000   
4          0.000000  0.750000  0.000000  0.166667  0.000000  0.000000   
...             ...       ...       ...       ...       ...       ...   
105286     0.000000  0.750000  0.000000  0.590280  0.458320  0.000000   
105287     0.000000  0.500000  0.000000  0.000000  0.000000  0.144427   
105288     0.385564  0.653609  0.192371  0.079519  0.614436  0.385564   
105289     0.000000  0.425066  0.000000  0.056676  0.000000  1.000000   
105290     0.000000  0.471805  0.000000  0.000000  0.000000  0.000000   

             Age  Education    Income  Diabetes_012  
0       0.750000   1.000000  0.857143           0.0  
1       0.333333   1.000000  1.000000           0.0  
2       1.000000   0.800000  0.714286           2.0  
3       0.750000   0.800000  0.714286           2.0  
4       0.583333   0.600000  0.571429           2.0  
...          ...        ...       ...           ...  
105286  0.312493   0.908336  1.000000           1.0  
105287  0.654631   0.828885  1.000000           1.0  
105288  0.602406   0.600000  0.000000           1.0  
105289  0.570844   0.940053  0.978590           1.0  
105290  0.759398   1.000000  1.000000           1.0  

[105291 rows x 22 columns]

In [6]:
y = df["Diabetes_012"]
X = df.drop(["Diabetes_012"], axis=1)

In [7]:
y

0         0.0
1         0.0
2         2.0
3         2.0
4         2.0
         ... 
105286    1.0
105287    1.0
105288    1.0
105289    1.0
105290    1.0
Name: Diabetes_012, Length: 105291, dtype: float64

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3)

In [11]:
knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)

In [12]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [13]:
pred_train = knn.predict(X_test)

In [14]:
pred_train

array([0., 0., 1., ..., 1., 0., 2.])

In [15]:
print("NO diabet", sum(pred_train==0))
print("PRE diabet", sum(pred_train==1))
print("YES diabet", sum(pred_train==2))

NO diabet 10809
PRE diabet 13124
YES diabet 11164


In [17]:
accuracy_score(y_test, pred_train)

0.7667321993332763

In [19]:
print(classification_report(y_test, pred_train))

              precision    recall  f1-score   support

         0.0       0.70      0.65      0.67     11666
         1.0       0.89      1.00      0.94     11779
         2.0       0.68      0.66      0.67     11652

    accuracy                           0.77     35097
   macro avg       0.76      0.77      0.76     35097
weighted avg       0.76      0.77      0.76     35097



In [21]:
confusion_matrix(y_test, pred_train)

array([[ 7535,   615,  3516],
       [   34, 11736,     9],
       [ 3240,   773,  7639]], dtype=int64)

## ROC AUC

In [25]:
pred_prob = knn.predict_proba(X_test)

In [26]:
pred_prob

array([[0.8, 0. , 0.2],
       [0.8, 0. , 0.2],
       [0. , 1. , 0. ],
       ...,
       [0. , 1. , 0. ],
       [0.8, 0. , 0.2],
       [0.2, 0. , 0.8]])

In [27]:
macro_roc_auc_ovr = roc_auc_score(
    y_test,
    pred_prob,
    multi_class="ovr",
    average="micro"
)

print(f"Macro-averaged One-vs-Rest ROC AUC score:\n{macro_roc_auc_ovr:.2f}")

Macro-averaged One-vs-Rest ROC AUC score:
0.91
