In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import roc_auc_score
from sklearn import metrics
from sklearn import svm, datasets
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV

In [2]:
df = pd.read_csv('../data/balanced_sclaer_dataset_diabetes.csv')

In [3]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [4]:
y = df["Diabetes_012"]
X = df.drop(["Diabetes_012"], axis=1)

In [5]:
y

0         0.0
1         2.0
2         0.0
3         0.0
4         2.0
         ... 
105286    1.0
105287    1.0
105288    1.0
105289    1.0
105290    1.0
Name: Diabetes_012, Length: 105291, dtype: float64

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3)

In [7]:
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics.pairwise import distance_metrics

In [8]:
knn_optimal = GridSearchCV(KNeighborsClassifier(), 
                                             {'n_neighbors': np.arange(3, 5, 1),
                                              'p': np.arange(1, 2, 1),
                                              "metric" : ["euclidean", "minkowski"]
                                              },
                                              ).fit(X_train, y_train)

In [9]:
# knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)

In [10]:
knn_optimal.fit(X_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'minkowski'],
                         'n_neighbors': array([3, 4]), 'p': array([1])})

In [11]:
pred_train = knn_optimal.predict(X_test)

In [12]:
X_test

HighBP  HighChol  CholCheck       BMI    Smoker  Stroke  \
14756      1.0       1.0        1.0  0.220930  1.000000     0.0   
58847      0.0       0.0        1.0  0.255814  1.000000     0.0   
65533      1.0       1.0        1.0  0.162791  0.000000     0.0   
10180      0.0       0.0        1.0  0.116279  1.000000     0.0   
49420      0.0       1.0        1.0  0.232558  1.000000     0.0   
...        ...       ...        ...       ...       ...     ...   
41511      1.0       1.0        1.0  0.093023  0.000000     0.0   
4793       1.0       1.0        1.0  0.220930  0.000000     0.0   
104704     1.0       1.0        1.0  0.290698  0.099317     0.0   
4949       1.0       1.0        1.0  0.127907  0.000000     0.0   
90133      1.0       1.0        1.0  0.186047  1.000000     0.0   

        HeartDiseaseorAttack  PhysActivity    Fruits   Veggies  ...  \
14756               0.000000           1.0  1.000000  1.000000  ...   
58847               0.000000           0.0  0.000000  1.000000  ...   
65533               0.000000           0.0  0.000000  0.000000  ...   
10180               0.000000           1.0  1.000000  1.000000  ...   
49420               0.000000           1.0  0.000000  1.000000  ...   
...                      ...           ...       ...       ...  ...   
41511               0.000000           0.0  1.000000  1.000000  ...   
4793                1.000000           0.0  0.000000  0.000000  ...   
104704              0.900683           1.0  0.099317  0.099317  ...   
4949                0.000000           1.0  1.000000  0.000000  ...   
90133               1.000000           0.0  1.000000  1.000000  ...   

        AnyHealthcare  NoDocbcCost   GenHlth  MentHlth  PhysHlth  DiffWalk  \
14756             1.0     0.000000  0.000000  0.000000  0.000000       0.0   
58847             1.0     0.000000  0.750000  1.000000  1.000000       1.0   
65533             1.0     0.000000  0.750000  0.033333  0.100000       0.0   
10180             1.0     0.000000  0.250000  0.233333  0.000000       0.0   
49420             1.0     0.000000  0.500000  0.000000  0.000000       0.0   
...               ...          ...       ...       ...       ...       ...   
41511             1.0     1.000000  0.750000  0.100000  0.000000       0.0   
4793              1.0     0.000000  0.750000  0.000000  0.066667       0.0   
104704            1.0     0.900683  0.475171  0.000000  0.000000       0.0   
4949              1.0     0.000000  0.250000  0.000000  0.000000       0.0   
90133             1.0     0.942801  1.000000  0.996187  0.988560       1.0   

             Sex       Age  Education    Income  
14756   0.000000  0.916667   0.600000  0.285714  
58847   0.000000  0.416667   1.000000  0.142857  
65533   0.000000  0.583333   0.400000  1.000000  
10180   0.000000  0.500000   1.000000  1.000000  
49420   0.000000  0.750000   1.000000  1.000000  
...          ...       ...        ...       ...  
41511   0.000000  0.916667   0.600000  0.428571  
4793    1.000000  0.666667   1.000000  0.857143  
104704  0.000000  0.750000   0.619863  0.285714  
4949    0.000000  0.750000   0.600000  0.285714  
90133   0.942801  0.666667   0.411440  0.142857  

[35097 rows x 21 columns]

In [13]:
pred_train

array([0., 0., 2., ..., 1., 2., 1.])

In [14]:
print("NO diabet", sum(pred_train==0))
print("PRE diabet", sum(pred_train==1))
print("YES diabet", sum(pred_train==2))

NO diabet 11294
PRE diabet 12079
YES diabet 11724


In [15]:
#MY_CLASSIFIER

In [16]:
# from MyKnnClassifier import MyKnnClassifier
# from MyKnnClassifier import euclid_distance

In [17]:
#MYMETRICS

In [18]:
# from Metrics import my_accuracy_score

In [19]:
# from Metrics import Metrics

In [20]:
# Metrics.my_precision(pred_train, y_test)

In [21]:
#SKLEARN_METRIC

In [22]:
#Accuracy
accuracy_score(y_test, pred_train)

0.7767330541071886

In [23]:
#Metrics
print(classification_report(y_test, pred_train))

              precision    recall  f1-score   support

         0.0       0.68      0.66      0.67     11675
         1.0       0.96      1.00      0.98     11588
         2.0       0.68      0.68      0.68     11834

    accuracy                           0.78     35097
   macro avg       0.77      0.78      0.78     35097
weighted avg       0.77      0.78      0.77     35097



In [24]:
#Conf_matrix
confusion_matrix(y_test, pred_train)

array([[ 7728,   232,  3715],
       [   24, 11544,    20],
       [ 3542,   303,  7989]], dtype=int64)

## ROC AUC

In [25]:
pred_prob = knn_optimal.predict_proba(X_test)

In [26]:
pred_prob

array([[0.66666667, 0.        , 0.33333333],
       [0.66666667, 0.        , 0.33333333],
       [0.        , 0.        , 1.        ],
       ...,
       [0.        , 1.        , 0.        ],
       [0.33333333, 0.        , 0.66666667],
       [0.        , 1.        , 0.        ]])

In [27]:
macro_roc_auc_ovr = roc_auc_score(
    y_test,
    pred_prob,
    multi_class="ovr",
    average="micro"
)

print(f"Macro-averaged One-vs-Rest ROC AUC score:\n{macro_roc_auc_ovr:.2f}")

Macro-averaged One-vs-Rest ROC AUC score:
0.90
