In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score, roc_curve, auc, RocCurveDisplay
from sklearn import metrics
from sklearn import svm, datasets
from itertools import cycle

In [2]:
df = pd.read_csv('../data/balanced_sclaer_dataset_diabetes.csv')

In [3]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [4]:
df

HighBP  HighChol  CholCheck       BMI    Smoker  Stroke  \
0       0.000000  0.000000   1.000000  0.174419  1.000000     0.0   
1       0.000000  1.000000   1.000000  0.220930  1.000000     0.0   
2       0.000000  0.000000   1.000000  0.174419  0.000000     0.0   
3       0.000000  0.000000   1.000000  0.151163  1.000000     0.0   
4       1.000000  1.000000   1.000000  0.209302  1.000000     0.0   
...          ...       ...        ...       ...       ...     ...   
105286  1.000000  1.000000   1.000000  0.250595  0.775591     0.0   
105287  1.000000  1.000000   1.000000  0.243025  0.900157     0.0   
105288  1.000000  0.699485   1.000000  0.330221  0.699485     0.0   
105289  0.508129  0.508129   1.000000  0.250095  0.508129     0.0   
105290  0.055528  1.000000   0.055528  0.184110  0.944472     0.0   

        HeartDiseaseorAttack  PhysActivity    Fruits   Veggies  ...  \
0                        0.0      1.000000  1.000000  1.000000  ...   
1                        1.0      1.000000  1.000000  1.000000  ...   
2                        0.0      1.000000  0.000000  1.000000  ...   
3                        0.0      1.000000  1.000000  1.000000  ...   
4                        0.0      0.000000  0.000000  0.000000  ...   
...                      ...           ...       ...       ...  ...   
105286                   0.0      0.000000  0.000000  0.775591  ...   
105287                   0.0      1.000000  0.099843  0.900157  ...   
105288                   0.0      0.300515  1.000000  1.000000  ...   
105289                   0.0      0.491871  0.508129  1.000000  ...   
105290                   0.0      0.055528  0.055528  1.000000  ...   

        NoDocbcCost   GenHlth  MentHlth  PhysHlth  DiffWalk       Sex  \
0          0.000000  0.250000  0.066667  0.000000  0.000000  0.000000   
1          0.000000  0.500000  0.000000  0.000000  0.000000  1.000000   
2          0.000000  0.500000  0.100000  0.000000  0.000000  0.000000   
3          0.000000  0.000000  0.033333  0.000000  0.000000  0.000000   
4          0.000000  0.500000  1.000000  0.000000  0.000000  0.000000   
...             ...       ...       ...       ...       ...       ...   
105286     0.224409  0.806102  0.462599  0.500000  1.000000  0.775591   
105287     0.000000  1.000000  1.000000  1.000000  0.099843  0.000000   
105288     0.000000  0.424871  0.000000  0.000000  0.000000  1.000000   
105289     0.000000  0.372968  0.016396  0.066667  0.000000  0.000000   
105290     0.944472  0.513882  0.229631  0.100000  0.000000  0.944472   

             Age  Education    Income  Diabetes_012  
0       0.166667   0.600000  0.000000           0.0  
1       0.583333   0.800000  0.857143           2.0  
2       0.500000   0.600000  0.714286           0.0  
3       0.500000   1.000000  0.857143           0.0  
4       0.250000   0.600000  1.000000           2.0  
...          ...        ...       ...           ...  
105286  0.750000   0.955118  0.728909           1.0  
105287  0.591654   0.619969  0.014263           1.0  
105288  0.525043   0.600000  1.000000           1.0  
105289  0.500000   1.000000  0.929733           1.0  
105290  0.495373   0.611106  0.007933           1.0  

[105291 rows x 22 columns]

In [5]:
df.isnull().sum().sum()

0

In [6]:
y = df["Diabetes_012"]
X = df.drop(["Diabetes_012"], axis=1)

In [7]:
y2 = y.to_numpy()
y2

array([0., 2., 0., ..., 1., 1., 1.])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3)

In [9]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

In [10]:
y_pred

array([2., 0., 1., ..., 2., 1., 2.])

In [11]:
print("NO diabet", sum(y_pred==0))
print("PRE diabet", sum(y_pred==1))
print("YES diabet", sum(y_pred==2))

NO diabet 11409
PRE diabet 12563
YES diabet 11125


In [12]:
#MY_METRICS

In [13]:
from Metrics import Metrics

In [14]:
y_test2 = list(map(int, y_test))
y_pred2 = list(map(int, y_pred))

In [15]:
Metrics.My_Confusion_matrix(y_test2, y_pred2)

Confusion Matrix :
Actual 0             6771            2665            2208           
Actual 1             2598            5996            3146           
Actual 2             2040            3902            5771           
{0: [6771, 2665, 2208], 1: [2598, 5996, 3146], 2: [2040, 3902, 5771]}


{0: [6771, 2665, 2208], 1: [2598, 5996, 3146], 2: [2040, 3902, 5771]}

In [16]:
#SKLEARN_METRICS

In [17]:
#Accuracy
accuracy_score(y_test, y_pred)

0.5281932928740348

In [18]:
#Metrics
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.59      0.58      0.59     11644
         1.0       0.48      0.51      0.49     11740
         2.0       0.52      0.49      0.51     11713

    accuracy                           0.53     35097
   macro avg       0.53      0.53      0.53     35097
weighted avg       0.53      0.53      0.53     35097



In [19]:
#Conf_matrix
confusion_matrix(y_test, y_pred)

array([[6771, 2665, 2208],
       [2598, 5996, 3146],
       [2040, 3902, 5771]], dtype=int64)

In [20]:
#ROC AUC

In [21]:
pred_prob = gnb.predict_proba(X_test)

In [22]:
macro_roc_auc_ovr = roc_auc_score(
    y_test,
    pred_prob,
    multi_class="ovr",
    average="micro"
)

print(f"Macro-averaged One-vs-Rest ROC AUC score:\n{macro_roc_auc_ovr:.2f}")

Macro-averaged One-vs-Rest ROC AUC score:
0.71


In [23]:
# n_classes = 3
# fpr = [0] * 3
# tpr = [0] * 3
# thresholds = [0] * 3
# auc_score = [0] * 3
 
# for i in range(n_classes):
#     print(pred_prob[:, i])
#     fpr[i], tpr[i], thresholds[i] = roc_curve(y_test[:, i],
#                                               pred_prob[:, i])
#     auc_score[i] = auc(fpr[i], tpr[i])
 
# auc_score