In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, RocCurveDisplay, auc
import tensorflow as tf

In [2]:
df = pd.read_csv('../Data/balanced_sclaer_dataset_diabetes.csv')
df.drop(['Unnamed: 0'], axis=1, inplace=True)
df.isnull().sum().sum()

0

In [3]:
y = df["Diabetes_012"]
X = df.drop(["Diabetes_012"], axis=1)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3)

In [5]:
y_train.to_numpy().shape

(70194,)

In [6]:
print(X.shape[1])

21


In [7]:
model_classification_1 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(X.shape[1],)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        # используем 2 нейрон и softmax
        tf.keras.layers.Dense(3, activation="softmax"),
    ]
)

In [8]:
model_classification_1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                1408      
                                                                 
 dense_1 (Dense)             (None, 128)               8320      
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_2 (Dense)             (None, 64)                8256      
                                                                 
 dense_3 (Dense)             (None, 32)                2080      
                                                                 
 dense_4 (Dense)             (None, 16)                528       
                                                                 
 dense_5 (Dense)             (None, 3)                 5

In [9]:
model_classification_1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005), loss="sparse_categorical_crossentropy")

In [10]:
model_classification_1.fit(X_train, y_train, epochs=25, verbose=None) #1m 4.5s

In [17]:
model_classification_1.save("../models/keras_mode_file.h5")

In [11]:
y_pred = np.around(model_classification_1.predict(X_test, verbose=None))

In [12]:
y_pred = pd.DataFrame(data= y_pred)

In [13]:
y_pred

0    1    2
0      1.0  0.0  0.0
1      1.0  0.0  0.0
2      1.0  0.0  0.0
3      1.0  0.0  0.0
4      1.0  0.0  0.0
...    ...  ...  ...
35092  1.0  0.0  0.0
35093  0.0  1.0  0.0
35094  0.0  0.0  1.0
35095  1.0  0.0  0.0
35096  1.0  0.0  0.0

[35097 rows x 3 columns]

In [14]:
y_pred_arg = [np.argmax(pred) for pred in model_classification_1.predict(X_test, verbose=None)]

In [15]:
y_pred_arg

[0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 2,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 2,
 1,
 2,
 1,
 2,
 1,
 0,
 2,
 0,
 1,
 2,
 0,
 0,
 1,
 1,
 2,
 0,
 1,
 2,
 2,
 1,
 2,
 2,
 0,
 1,
 0,
 1,
 2,
 1,
 0,
 0,
 2,
 0,
 2,
 0,
 1,
 2,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 2,
 0,
 0,
 2,
 2,
 1,
 1,
 0,
 2,
 2,
 2,
 2,
 0,
 1,
 2,
 1,
 0,
 0,
 0,
 2,
 2,
 1,
 2,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 2,
 0,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 1,
 0,
 2,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 1,
 0,
 2,
 0,
 1,
 0,
 2,
 1,
 0,
 2,
 0,
 2,
 2,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 2,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 2,
 2,
 2,
 0,
 1,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 2,
 2,
 0,
 1,
 2,
 2,
 2,
 0,
 0,
 0,
 1,
 1,
 2,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 2,
 2,
 1,
 2,
 0,
 2,
 0,
 0,
 1,
 1,
 1,
 2,
 0,
 0,
 2,
 0,
 0,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 1,
 2,
 2,
 1,
 0,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 0,
 0,
 1,
 1,
 0,
 2,
 0,
 1,
 1,


In [16]:
print(classification_report(y_test, y_pred_arg))
print(confusion_matrix(y_test, y_pred_arg))

              precision    recall  f1-score   support

         0.0       0.68      0.75      0.72     11686
         1.0       0.98      0.88      0.93     11728
         2.0       0.70      0.70      0.70     11683

    accuracy                           0.78     35097
   macro avg       0.79      0.78      0.78     35097
weighted avg       0.79      0.78      0.78     35097

[[ 8782   146  2758]
 [  616 10330   782]
 [ 3457    90  8136]]
